services:
  db:
    image: postgres:16
    container_name: poptop_postgres
    restart: always
    environment:
      POSTGRES_DB: booking_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: booking_web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
      DB_NAME: booking_platform
      DB_USER: admin
      DB_PASSWORD: admin_password
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data: